name: app_notas_v2
description: "Aplicacion para el Registro de notas"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.2
  go_router: ^14.3.0
  flutter_launcher_icons: ^0.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/img/
  uses-material-design: true

flutter_icons:
  android: "assets/icon/icon.jpeg"